### ISSUE TITLE
Error message in the documentation

### ISSUE THREAD

**Issue by lofsgaard** [dynatrace-extensions/dt-extensions-python-sdk#41]
Not sure any of the templates fit this, but I wanted to let you know that this page: https://dynatrace-extensions.github.io/dt-extensions-python-sdk/cli/create.html

Is showing a python error and not the expected output of ```dt-sdk create --help```

```
Traceback (most recent call last):
  File "/home/runner/.local/share/hatch/env/virtual/dt-extensions-sdk/DWb-hKQH/docs/bin/dt-sdk", line 5, in <module>
    from dynatrace_extension.cli import app
  File "/home/runner/work/dt-extensions-python-sdk/dt-extensions-python-sdk/dynatrace_extension/cli/__init__.py", line 5, in <module>
    from .main import app  # noqa: F401
  File "/home/runner/work/dt-extensions-python-sdk/dt-extensions-python-sdk/dynatrace_extension/cli/main.py", line 12, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
```

**Comment by lofsgaard** [comment]
After further investigation it seems to be a problem on all the links under "All commands"

**Comment by dlopes7** [comment]
I'm sorry about that, you manage to get version 1.1.12 whoch was released in a very short window.

1.1.13 has the fix

**Comment by dlopes7** [comment]
We will retrigger the docs

**Comment by dlopes7** [comment]
It should be live now after a hard refresh of the browser, thanks!
